disableKinds = ["RSS"]

baseURL = "https://vikisses.github.io/hugo_portfolio/"
languageCode = "ru-ru"
title = "Portfolio"
theme = "PaperMod"

[author]
  name = "Виктория Тарасова"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

[menu]
  [[menu.main]]
    name = "Обо мне"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "Проекты"
    url = "/projects/"
    weight = 2